language: ruby

services:
  - postgresql

addons:
  postgresql: "9.6"

jobs:
  include:
    - stage: test
      before_script:
        - bin/rails db:setup
      script:
        - bundle exec rspec
    - script: bundle exec rubocop
