version: 2.1

# See https://circleci.com/docs/2.0/reusing-config
commands:
  install_dependencies:
    description: "Ensure that all dependencies are installed"
    steps:
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install

  prepare_repo:
    steps:
      - restore_cache:
          keys:
          - checkout-{{ .Environment.CIRCLE_SHA1 }}
      - install_dependencies

  prepare_database:
    description: "Install Postgres client and load db structure"
    steps:
      - run: sudo apt install -y postgresql-client || true
      - run: bundle exec rake db:structure:load

jobs:
  prepare:
    working_directory: ~/repo
    docker:
       - image: circleci/ruby:2.6.0-node-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - install_dependencies

      - save_cache:
          paths:
            - ./vendor/bundle
            - ./node_modules
          key: dependencies-{{ checksum "Gemfile.lock" }}

      - save_cache:
          paths: ~/repo
          key: checkout-{{ .Environment.CIRCLE_SHA1 }}

  test:
    working_directory: ~/repo

    docker:
       - image: circleci/ruby:2.6.0-node-browsers
       - image: circleci/postgres:10.6-alpine-ram
         environment:
           POSTGRES_USER: root
           POSTGRES_DB: test
       - image: circleci/redis:latest

    environment:
      DATABASE_URL: "postgresql://root@localhost/test"
      RAILS_ENV: test

    steps:
      - prepare_repo
      - prepare_database

      - run:
          name: run tests
          command: |
            mkdir -p /tmp/rspec/test-results
            bundle exec rspec --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec/results.xml \
                              --format documentation

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - store_artifacts:
          path: ./coverage
          destination: coverage

  rubocop:
    working_directory: ~/repo

    docker:
       - image: circleci/ruby:2.6.0-node-browsers

    steps:
      - prepare_repo
      - run: bundle exec rubocop

workflows:
  version: 2
  test:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - rubocop:
          requires:
            - prepare
